@extends('layouts.app')
@php $pageTitle = 'New Request'; @endphp
@section('content')

<div class="page-header">
    <div class="page-title">New Purchase Request</div>
    <div class="page-desc">Fill in the form below to submit a new procurement request.</div>
</div>

<form action="{{ route('purchase_requests.store') }}" method="post" id="pr-form">
@csrf

<!-- SECTION 1: Request Information -->
<div class="card">
    <div class="card-header">
        <div class="flex-center">
            <div class="form-section-icon">
                <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="9" y="2" width="6" height="4" rx="1"/><path d="M7 2H5a2 2 0 00-2 2v16a2 2 0 002 2h14a2 2 0 002-2V4a2 2 0 00-2-2h-2" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </div>
            <div>
                <div class="card-title">Request Information</div>
                <div class="card-desc">ID and date are auto-generated by the system</div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="form-row form-row-2" style="gap:16px;">
            <div class="form-group">
                <label class="form-label">Request ID</label>
                <input class="form-control" disabled value="PR-{{ now()->format('Y') }}-{{ now()->format('md') }}-XXX">
            </div>
            <div class="form-group">
                <label class="form-label">Submission Date</label>
                <input class="form-control" disabled value="{{ now()->format('d /m/ Y') }}">
            </div>
        </div>
        <div class="form-row form-row-2 mt-3" style="gap:16px;">
            <div class="form-group">
                <label class="form-label" for="need_date">Required Date <span class="req">*</span></label>
                <input class="form-control" type="date" id="need_date" name="need_date" value="{{ old('need_date') }}" required>
            </div>
            <div class="form-group">
                <label class="form-label" for="plant">Plant <span class="req">*</span></label>
                <select class="form-control" id="plant" name="plant" required>
                    <option value="">— Select Plant —</option>
                    @foreach(['Cikarang','Cibitung','Gresik'] as $p)
                    <option value="{{ $p }}" {{ old('plant') === $p ? 'selected' : '' }}>{{ $p }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="form-group mt-3">
            <label class="form-label" for="pr-notes">Notes</label>
            <textarea class="form-control" id="pr-notes" name="note" placeholder="Add any additional notes here..." style="min-height:80px;">{{ old('note') }}</textarea>
        </div>
    </div>
</div>

<!-- SECTION 2: Requester Information -->
<div class="card mt-4">
    <div class="card-header">
        <div class="flex-center">
            <div class="form-section-icon">
                <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
            </div>
            <div>
                <div class="card-title">Requester Information</div>
                <div class="card-desc">Populated automatically from your account</div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="form-row form-row-3" style="gap:16px;">
            <div class="form-group">
                <label class="form-label">Full Name</label>
                <input class="form-control" disabled value="{{ Auth::user()->name }}">
            </div>
            <div class="form-group">
                <label class="form-label">Department</label>
                <input class="form-control" name="department" value="{{ old('department', Auth::user()->department ?? '') }}" required>
            </div>
            <div class="form-group">
                <label class="form-label">Position / Role</label>
                <input class="form-control" disabled value="{{ ucfirst(Auth::user()->role ?? 'Staff') }}">
            </div>
        </div>
        <div class="form-group mt-3">
            <label class="form-label" for="title">PR Title / Description <span class="req">*</span></label>
            <input class="form-control" type="text" id="title" name="title" value="{{ old('title') }}" placeholder="e.g. Pengadaan Kabel NYY & MCB" required>
        </div>
    </div>
</div>

<!-- SECTION 3: Items / Service -->
<div class="card mt-4">
    <div class="card-header">
        <div class="flex-center">
            <div class="form-section-icon">
                <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M20 7H4a2 2 0 00-2 2v10a2 2 0 002 2h16a2 2 0 002-2V9a2 2 0 00-2-2z"/><path d="M16 7V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v2" stroke-linecap="round"/></svg>
            </div>
            <div>
                <div class="card-title" id="section-title">Purchase Items</div>
            </div>
        </div>
    </div>
    <div class="card-body">

        <!-- Tabs -->
        <div style="display:flex;gap:8px;margin-bottom:20px;">
            <button type="button" id="tab-goods" class="tab-btn tab-active" onclick="setTab('goods')">🛒 Goods</button>
            <button type="button" id="tab-service" class="tab-btn" onclick="setTab('service')">🔧 Service</button>
        </div>
        <input type="hidden" name="item_type" id="item_type_field" value="goods">

        <!-- ── GOODS PANEL ── -->
        <div id="goods-panel">
            <div class="flex-between" style="margin-bottom:14px;">
                <div class="text-sm text-muted" id="goods-count-label">0 item(s) added</div>
                <button type="button" class="btn btn-primary btn-sm" onclick="openItemModal()">
                    <svg width="12" height="12" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14" stroke-linecap="round"/></svg>
                    Add Item
                </button>
            </div>
            <div style="border:1px solid var(--border);border-radius:10px;overflow:hidden;">
                <table style="width:100%;border-collapse:collapse;font-size:13.5px;">
                    <thead>
                        <tr style="background:#f9fafb;">
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;width:36px;">NO</th>
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;">ITEM ID</th>
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;">ITEM NAME</th>
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;">DESCRIPTION</th>
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;width:70px;">QTY</th>
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;width:80px;">UNIT</th>
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;">SPECIFICATION</th>
                            <th style="padding:9px 14px;width:36px;"></th>
                        </tr>
                    </thead>
                    <tbody id="goods-tbody">
                        <tr><td colspan="8" style="text-align:center;padding:28px 16px;color:#9ca3af;font-size:13.5px;">No items added yet. Click "Add Item" to begin.</td></tr>
                    </tbody>
                </table>
            </div>
        </div>

        <!-- ── SERVICE PANEL ── -->
        <div id="service-panel" style="display:none;">
            <div class="flex-between" style="margin-bottom:14px;">
                <div class="text-sm text-muted" id="svc-count-label">0 item(s) added</div>
                <button type="button" class="btn btn-primary btn-sm" onclick="openServiceModal()">
                    <svg width="12" height="12" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14" stroke-linecap="round"/></svg>
                    Add Row
                </button>
            </div>
            <div style="border:1px solid var(--border);border-radius:10px;overflow:hidden;">
                <table style="width:100%;border-collapse:collapse;font-size:13.5px;">
                    <thead>
                        <tr style="background:#f9fafb;">
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;width:40px;">NO</th>
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;width:160px;">SERVICE ID</th>
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;">JOB DESCRIPTION</th>
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;width:90px;">UNIT</th>
                            <th style="padding:9px 14px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;width:90px;">VOL</th>
                            <th style="padding:9px 14px;width:36px;"></th>
                        </tr>
                    </thead>
                    <tbody id="svc-tbody">
                        <tr><td colspan="6" style="text-align:center;padding:28px 16px;color:#9ca3af;font-size:13.5px;">No service details added yet. Click "Add Row" to begin.</td></tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>

<!-- ACTIONS -->
<div style="display:flex;justify-content:flex-end;gap:12px;margin-top:24px;">
    <a href="{{ route('dashboard') }}" class="btn btn-outline">Cancel</a>
    <button type="submit" class="btn btn-primary">Submit Request</button>
</div>
</form>

<!-- ════ GOODS: SELECT ITEM MODAL ════ -->
<div class="modal-overlay" id="item-modal">
    <div class="modal">
        <div class="modal-header">
            <div><div class="modal-title">Select Item</div><div class="modal-desc">Search existing items or create a new one</div></div>
            <button class="modal-close" onclick="closeItemModal()"><svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12" stroke-linecap="round"/></svg></button>
        </div>
        <div class="modal-body">
            <input class="form-control" id="item-search" placeholder="Search by ID, name, or description..." oninput="filterItems(this.value)" style="margin-bottom:14px;">
            <div id="item-list" style="display:flex;flex-direction:column;gap:2px;"></div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-outline" onclick="closeItemModal()">Cancel</button>
            <button class="btn btn-primary" onclick="addSelectedItem()">Add Selected Item</button>
        </div>
    </div>
</div>

<!-- GOODS: CREATE NEW ITEM MODAL -->
<div class="modal-overlay" id="new-item-modal">
    <div class="modal">
        <div class="modal-header">
            <div><div class="modal-title">Create New Item</div><div class="modal-desc">Add a new item to the system catalog</div></div>
            <button class="modal-close" onclick="closeNewItemModal()"><svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12" stroke-linecap="round"/></svg></button>
        </div>
        <div class="modal-body">
            <div class="form-row form-row-2" style="gap:14px;">
                <div class="form-group"><label class="form-label">Item Name <span class="req">*</span></label><input class="form-control" id="new-item-name" placeholder="e.g. Kabel NYY 4x10mm"></div>
                <div class="form-group"><label class="form-label">Unit <span class="req">*</span></label>
                    <select class="form-control" id="new-item-unit"><option>Roll</option><option>Pcs</option><option>Unit</option><option>Batang</option><option>Meter</option><option>Kg</option><option>Liter</option><option>Set</option></select>
                </div>
            </div>
            <div class="form-group mt-3"><label class="form-label">Description</label><input class="form-control" id="new-item-desc" placeholder="Brief description"></div>
            <div class="form-group mt-3"><label class="form-label">Specification</label><textarea class="form-control" id="new-item-spec" placeholder="Technical specifications..." style="min-height:70px;"></textarea></div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-outline" onclick="closeNewItemModal()">Cancel</button>
            <button class="btn btn-primary" onclick="saveNewItem()">Save & Add Item</button>
        </div>
    </div>
</div>

<!-- ════ SERVICE: SELECT SERVICE MODAL ════ -->
<div class="modal-overlay" id="svc-select-modal">
    <div class="modal">
        <div class="modal-header">
            <div><div class="modal-title">Select Service</div><div class="modal-desc">Search existing service scope from template</div></div>
            <button class="modal-close" onclick="closeSvcSelectModal()"><svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12" stroke-linecap="round"/></svg></button>
        </div>
        <div class="modal-body">
            <input class="form-control" id="svc-search" placeholder="Search by job description..." oninput="filterServices(this.value)" style="margin-bottom:14px;">
            <div id="svc-list" style="display:flex;flex-direction:column;gap:2px;"></div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-outline" onclick="closeSvcSelectModal()">Cancel</button>
            <button class="btn btn-primary" onclick="addSelectedService()">Add Selected Service</button>
        </div>
    </div>
</div>

<!-- SERVICE: CREATE NEW SERVICE SCOPE MODAL -->
<div class="modal-overlay" id="svc-create-modal">
    <div class="modal" style="max-width:480px;">
        <div class="modal-header">
            <div><div class="modal-title">Create New Service Scope</div><div class="modal-desc">Register a new service with a unique ID</div></div>
            <button class="modal-close" onclick="closeSvcCreateModal()"><svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12" stroke-linecap="round"/></svg></button>
        </div>
        <div class="modal-body">
            <div class="form-group"><label class="form-label">Service ID</label><input class="form-control" id="new-svc-id" readonly style="background:#f9fafb;color:#6b7280;"></div>
            <div class="form-group mt-3"><label class="form-label">Job Description <span class="req">*</span></label><input class="form-control" id="new-svc-desc" placeholder="e.g. Bongkar Paving"></div>
            <div class="form-row form-row-2 mt-3" style="gap:14px;">
                <div class="form-group"><label class="form-label">Unit</label><input class="form-control" id="new-svc-unit" value="m2" placeholder="m2, ls, unit..."></div>
                <div class="form-group"><label class="form-label">Volume</label><input class="form-control" type="number" id="new-svc-vol" value="1" min="1"></div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-outline" onclick="backToSvcSelect()">Back</button>
            <button class="btn btn-primary" onclick="saveNewService()">Save Service Scope</button>
        </div>
    </div>
</div>

<!-- SUCCESS MODAL (shown after flash) -->
<div class="modal-overlay" id="success-modal" style="display:none;">
    <div class="modal" style="max-width:440px;">
        <div class="modal-body" style="padding:36px 28px;text-align:center;">
            <div style="width:52px;height:52px;background:#f0fdf4;border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 16px;">
                <svg width="24" height="24" fill="none" stroke="#16a34a" stroke-width="2.5" viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"/></svg>
            </div>
            <div style="font-size:16px;font-weight:700;color:#111827;margin-bottom:6px;" id="success-title">Request submitted successfully!</div>
            <div style="font-size:14px;color:#6b7280;" id="success-body">Your request has been sent for approval.</div>
        </div>
        <div class="modal-footer" style="justify-content:center;padding-bottom:24px;">
            <a href="{{ route('pr.list') }}" class="btn btn-outline">Close</a>
        </div>
    </div>
</div>

<style>
.tab-btn { padding:7px 18px;border-radius:8px;border:1px solid var(--border);font-size:13.5px;font-weight:600;cursor:pointer;background:white;color:var(--text-muted);transition:all .15s;font-family:inherit; }
.tab-btn.tab-active { background:#111827;color:white;border-color:#111827; }
.item-option { padding:12px 14px;border-radius:8px;cursor:pointer;border:1px solid transparent;transition:background .1s,border-color .1s; }
.item-option:hover { background:#f9fafb; }
.item-option.selected { background:var(--primary-light);border-color:var(--primary); }
.item-option-id { font-size:11.5px;font-weight:700;color:var(--primary);font-family:monospace; }
.item-option-name { font-size:13.5px;font-weight:600;color:var(--text);margin-top:1px; }
.item-option-desc { font-size:12px;color:var(--text-muted);margin-top:2px; }
.create-new-btn { padding:12px 14px;border-radius:8px;cursor:pointer;border:1px dashed var(--border-strong);background:transparent;font-size:13.5px;font-weight:600;color:var(--primary);display:flex;align-items:center;gap:8px;width:100%;margin-top:6px;font-family:inherit;transition:background .1s; }
.create-new-btn:hover { background:var(--primary-light); }
</style>

<script>
// ── Catalogs ──────────────────────────────────────────────────────────────────
const catalog = [
    { id:'ITM-0007', name:'MCB 3 Phase 40A',      desc:'Circuit breaker 3 phase untuk panel distribusi listrik', unit:'Pcs',   spec:'Schneider Easy9, 3P, 40A, 6kA' },
    { id:'ITM-0008', name:'MCB 1 Phase 16A',       desc:'Circuit breaker 1 phase untuk sub panel',                unit:'Pcs',   spec:'Schneider Easy9, 1P, 16A, 6kA' },
    { id:'ITM-0009', name:'Schneider MCCB 3P 63A', desc:'Molded case circuit breaker 3 phase 63A',               unit:'Pcs',   spec:'Schneider EasyPact, 63A' },
    { id:'ITM-0012', name:'APC Smart-UPS 3000VA',  desc:'Uninterruptible power supply untuk server room',        unit:'Unit',  spec:'APC SMT3000I, 3000VA' },
    { id:'ITM-0021', name:'Kabel NYY 4x10mm',      desc:'Kabel daya utama, standar PLN',                         unit:'Roll',  spec:'4 core, 10mm², 0.6/1kV' },
    { id:'ITM-0022', name:'Kabel NYY 4x6mm',       desc:'Kabel daya cabang',                                     unit:'Roll',  spec:'4 core, 6mm², 0.6/1kV' },
    { id:'ITM-0031', name:'Conduit PVC 20mm',      desc:'Pelindung jalur kabel',                                  unit:'Batang',spec:'Clipsal Heavy Duty, 3m/batang' },
];

const svcCatalog = [
    { id:'SVC-001', desc:'Mob dan demobilisasi material & alat bantu', unit:'ls' },
    { id:'SVC-002', desc:'Mess Pekerja dan Akomodasi',                 unit:'ls' },
    { id:'SVC-003', desc:'Peralatan safety pekerja K3',                unit:'ls' },
    { id:'SVC-004', desc:'Bongkar beton Dam',                          unit:'m3' },
    { id:'SVC-005', desc:'Galian tanah biasa',                         unit:'m3' },
    { id:'SVC-006', desc:'Pengecoran beton K-250',                     unit:'m3' },
    { id:'SVC-007', desc:'Pasangan bata ringan',                       unit:'m2' },
];

let selectedItemId = null, selectedSvcId = null;
let addedItems = [], addedServices = [];
let itemCounter = 0, svcCounter = 0;

// ── Tab ───────────────────────────────────────────────────────────────────────
function setTab(t) {
    document.getElementById('item_type_field').value = t;
    document.getElementById('tab-goods').classList.toggle('tab-active', t==='goods');
    document.getElementById('tab-service').classList.toggle('tab-active', t==='service');
    document.getElementById('goods-panel').style.display   = t==='goods'   ? '' : 'none';
    document.getElementById('service-panel').style.display = t==='service' ? '' : 'none';
    document.getElementById('section-title').textContent   = t==='goods' ? 'Purchase Items' : 'Service Requirements';
}

// ── GOODS ─────────────────────────────────────────────────────────────────────
function filterItems(q) { renderItemList(q.toLowerCase()); }
function renderItemList(q='') {
    const filtered = catalog.filter(i=>!q||i.id.toLowerCase().includes(q)||i.name.toLowerCase().includes(q)||i.desc.toLowerCase().includes(q));
    document.getElementById('item-list').innerHTML = filtered.map(i=>`
        <div class="item-option ${selectedItemId===i.id?'selected':''}" onclick="selectItem('${i.id}')">
            <div class="item-option-id">${i.id}</div>
            <div class="item-option-name">${i.name}</div>
            <div class="item-option-desc">${i.desc}</div>
        </div>`).join('')+`
        <button type="button" class="create-new-btn" onclick="openNewItemModal()">
            <svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14" stroke-linecap="round"/></svg>
            Create New Item ID
        </button>`;
}
function selectItem(id){ selectedItemId=id; renderItemList(document.getElementById('item-search').value.toLowerCase()); }
function openItemModal(){ selectedItemId=null; document.getElementById('item-search').value=''; renderItemList(); document.getElementById('item-modal').classList.add('open'); }
function closeItemModal(){ document.getElementById('item-modal').classList.remove('open'); }
function addSelectedItem(){
    if(!selectedItemId){alert('Please select an item first.');return;}
    const i=catalog.find(x=>x.id===selectedItemId); if(!i)return;
    const idx=itemCounter++; addedItems.push({idx,id:i.id,name:i.name,desc:i.desc,unit:i.unit,spec:i.spec,qty:1});
    renderGoodsTable(); document.getElementById('goods-count-label').textContent=`${addedItems.length} item(s) added`;
    closeItemModal();
}
function renderGoodsTable(){
    const t=document.getElementById('goods-tbody');
    if(!addedItems.length){t.innerHTML='<tr><td colspan="8" style="text-align:center;padding:28px 16px;color:#9ca3af;">No items added yet. Click "Add Item" to begin.</td></tr>';return;}
    t.innerHTML=addedItems.map((it,i)=>`<tr>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;color:#6b7280;">${i+1}</td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;font-family:monospace;font-size:12px;color:var(--primary);font-weight:600;">${it.id}<input type="hidden" name="items[${it.idx}][item_code]" value="${it.id}"></td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;font-weight:500;">${it.name}<input type="hidden" name="items[${it.idx}][name]" value="${it.name}"></td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;font-size:12px;color:#6b7280;">${it.desc}<input type="hidden" name="items[${it.idx}][unit]" value="${it.unit}"></td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;"><input type="number" name="items[${it.idx}][quantity]" value="${it.qty}" min="1" style="width:60px;padding:5px 8px;border:1px solid #d1d5db;border-radius:6px;font-size:13px;" onchange="addedItems.find(x=>x.idx==${it.idx}).qty=this.value"></td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;font-size:13px;">${it.unit}</td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;font-size:12px;color:#6b7280;">${it.spec||'—'}<input type="hidden" name="items[${it.idx}][specification]" value="${it.spec||''}"></td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;"><button type="button" onclick="removeGoods(${it.idx})" style="background:none;border:none;cursor:pointer;color:#9ca3af;padding:4px;border-radius:6px;" onmouseover="this.style.color='#dc2626'" onmouseout="this.style.color='#9ca3af'"><svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12" stroke-linecap="round"/></svg></button></td>
    </tr>`).join('');
}
function removeGoods(idx){ addedItems=addedItems.filter(i=>i.idx!==idx); renderGoodsTable(); document.getElementById('goods-count-label').textContent=`${addedItems.length} item(s) added`; }
function openNewItemModal(){ closeItemModal(); document.getElementById('new-item-modal').classList.add('open'); }
function closeNewItemModal(){ document.getElementById('new-item-modal').classList.remove('open'); }
function saveNewItem(){
    const name=document.getElementById('new-item-name').value.trim();
    if(!name){alert('Item name is required.');return;}
    const unit=document.getElementById('new-item-unit').value;
    const desc=document.getElementById('new-item-desc').value.trim();
    const spec=document.getElementById('new-item-spec').value.trim();
    const newId='ITM-'+String(Math.floor(Math.random()*9000+1000)).padStart(4,'0');
    catalog.push({id:newId,name,desc,unit,spec});
    const idx=itemCounter++; addedItems.push({idx,id:newId,name,desc,unit,spec,qty:1});
    renderGoodsTable(); document.getElementById('goods-count-label').textContent=`${addedItems.length} item(s) added`;
    closeNewItemModal();
    ['new-item-name','new-item-desc','new-item-spec'].forEach(id=>document.getElementById(id).value='');
}

// ── SERVICE ───────────────────────────────────────────────────────────────────
function filterServices(q){ renderSvcList(q.toLowerCase()); }
function renderSvcList(q=''){
    const filtered=svcCatalog.filter(s=>!q||s.id.toLowerCase().includes(q)||s.desc.toLowerCase().includes(q));
    document.getElementById('svc-list').innerHTML=filtered.map(s=>`
        <div class="item-option ${selectedSvcId===s.id?'selected':''}" onclick="selectSvc('${s.id}')">
            <div class="item-option-id">${s.id}</div>
            <div class="item-option-name">${s.desc}</div>
            <div class="item-option-desc">Standard unit: ${s.unit}</div>
        </div>`).join('')+`
        <button type="button" class="create-new-btn" onclick="openSvcCreateModal()">
            <svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14" stroke-linecap="round"/></svg>
            Create New Service ID
        </button>`;
}
function selectSvc(id){ selectedSvcId=id; renderSvcList(document.getElementById('svc-search').value.toLowerCase()); }
function openServiceModal(){ selectedSvcId=null; document.getElementById('svc-search').value=''; renderSvcList(); document.getElementById('svc-select-modal').classList.add('open'); }
function closeSvcSelectModal(){ document.getElementById('svc-select-modal').classList.remove('open'); }
function addSelectedService(){
    if(!selectedSvcId){alert('Please select a service first.');return;}
    const s=svcCatalog.find(x=>x.id===selectedSvcId); if(!s)return;
    const idx=svcCounter++; addedServices.push({idx,id:s.id,desc:s.desc,unit:s.unit,vol:1});
    renderSvcTable(); document.getElementById('svc-count-label').textContent=`${addedServices.length} item(s) added`;
    closeSvcSelectModal();
}
function renderSvcTable(){
    const t=document.getElementById('svc-tbody');
    if(!addedServices.length){t.innerHTML='<tr><td colspan="6" style="text-align:center;padding:28px 16px;color:#9ca3af;">No service details added yet. Click "Add Row" to begin.</td></tr>';return;}
    t.innerHTML=addedServices.map((s,i)=>`<tr>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;color:#6b7280;">${i+1}</td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;font-family:monospace;font-size:12px;color:var(--primary);font-weight:600;">${s.id}<input type="hidden" name="services[${s.idx}][service_id]" value="${s.id}"></td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;font-weight:500;">${s.desc}<input type="hidden" name="services[${s.idx}][description]" value="${s.desc}"></td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;font-size:13px;">${s.unit}<input type="hidden" name="services[${s.idx}][unit]" value="${s.unit}"></td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;"><input type="number" name="services[${s.idx}][volume]" value="${s.vol}" min="1" style="width:60px;padding:5px 8px;border:1px solid #d1d5db;border-radius:6px;font-size:13px;" onchange="addedServices.find(x=>x.idx==${s.idx}).vol=this.value"></td>
        <td style="padding:11px 14px;border-bottom:1px solid #f3f4f6;"><button type="button" onclick="removeSvc(${s.idx})" style="background:none;border:none;cursor:pointer;color:#9ca3af;padding:4px;border-radius:6px;" onmouseover="this.style.color='#dc2626'" onmouseout="this.style.color='#9ca3af'"><svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12" stroke-linecap="round"/></svg></button></td>
    </tr>`).join('');
}
function removeSvc(idx){ addedServices=addedServices.filter(s=>s.idx!==idx); renderSvcTable(); document.getElementById('svc-count-label').textContent=`${addedServices.length} item(s) added`; }

function openSvcCreateModal(){
    closeSvcSelectModal();
    const next='SVC-'+String(svcCatalog.length+1).padStart(3,'0');
    document.getElementById('new-svc-id').value=next;
    ['new-svc-desc'].forEach(id=>document.getElementById(id).value='');
    document.getElementById('new-svc-unit').value='m2';
    document.getElementById('new-svc-vol').value='1';
    document.getElementById('svc-create-modal').classList.add('open');
}
function closeSvcCreateModal(){ document.getElementById('svc-create-modal').classList.remove('open'); }
function backToSvcSelect(){ closeSvcCreateModal(); openServiceModal(); }
function saveNewService(){
    const id=document.getElementById('new-svc-id').value.trim();
    const desc=document.getElementById('new-svc-desc').value.trim();
    if(!desc){alert('Job description is required.');return;}
    const unit=document.getElementById('new-svc-unit').value.trim()||'ls';
    const vol=parseInt(document.getElementById('new-svc-vol').value)||1;
    svcCatalog.push({id,desc,unit});
    const idx=svcCounter++; addedServices.push({idx,id,desc,unit,vol});
    renderSvcTable(); document.getElementById('svc-count-label').textContent=`${addedServices.length} item(s) added`;
    closeSvcCreateModal();
}

// ── Validate submit ───────────────────────────────────────────────────────────
document.getElementById('pr-form').addEventListener('submit',function(e){
    const type=document.getElementById('item_type_field').value;
    if(type==='goods'&&addedItems.length===0){e.preventDefault();alert('Please add at least one item before submitting.');return;}
    if(type==='service'&&addedServices.length===0){e.preventDefault();alert('Please add at least one service before submitting.');return;}
});

// ── Overlay close ─────────────────────────────────────────────────────────────
['item-modal','new-item-modal','svc-select-modal','svc-create-modal'].forEach(id=>{
    document.getElementById(id).addEventListener('click',function(e){if(e.target===this)this.classList.remove('open');});
});

// ── Success modal on flash ────────────────────────────────────────────────────
@if(session('success'))
    const sm=document.getElementById('success-modal');
    sm.style.display='flex'; sm.classList.add('open');
    const m='{{ session("success") }}'.match(/(PR-[\w-]+)/);
    if(m){
        document.getElementById('success-title').textContent='Request submitted successfully!';
        document.getElementById('success-body').textContent=m[0]+' has been sent for approval.';
    }
@endif
</script>

@endsection